/*
 * voltdrum_protocoll.h
 *
 *  Created on: 09.02.2016
 *      Author: raphael
 */

#ifndef INC_VOLTDRUM_PROTOCOLL_H_
#define INC_VOLTDRUM_PROTOCOLL_H_


/*BITFILTER*/
#define MASK_TYPE 0b10000000
#define MASK_CONTENT 0b01111111

/*CMD Types*/
#define CMD_TYPE_DRUMTRIGGER 0x00
#define CMD_TYPE_HIHAT 0x01
#define CMD_TYPE_BUTTON 0x02
#define CMD_TYPE_CONFIG_SEND 0x03
#define CMD_TYPE_CONFIG_REQ 0x04
#define CMD_TYPE_CONFIG_RESP 0x05
#define CMD_TYPE_RESET 0x06

/*Config-Types*/
#define CONFIG_TYPE_MIDINOTE 0x00
#define CONFIG_TYPE_THRESHOLD_STATIC 0x01
#define CONFIG_TYPE_THRESHOLD_DYNAMIC 0x02
#define CONFIG_TYPE_SAMPLES_TO_TAKE 0x03
#define CONFIG_TYPE_TIMEOFFSET 0x04
#define CONFIG_TYPE_LASTSAMPLESBUFFER 0x05

/*CMD SIZES*/
#define CMD_SIZE_DRUMTRIGGER 3
#define CMD_SIZE_HIHAT 3
#define CMD_SIZE_BUTTON 3
#define CMD_SIZE_CONFIG_SEND 5
#define CMD_SIZE_CONFIG_REQ 3
#define CMD_SIZE_CONFIG_RESP 5
#define CMD_SIZE_RESET 3




#endif /* INC_VOLTDRUM_PROTOCOLL_H_ */
